CREATE TABLE IF NOT EXISTS token(
	userId INT NOT NULL,
	content VARCHAR(256) NOT NULL,
	expireAt DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL 2 WEEK),
	PRIMARY KEY (userId),
	FOREIGN KEY (userId) REFERENCES user(id));
