CREATE TABLE if not exists user (
	id INT NOT NULL,
	name VARCHAR(64) NOT NULL UNIQUE,
	profileImage VARCHAR(256) NOT NULL,
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
