CREATE TABLE IF NOT EXISTS push_subscription (
	id INT NOT NULL AUTO_INCREMENT,
	sub VARCHAR(1024) NOT NULL UNIQUE,
	userId INT NOT NULL,
	updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (userId) REFERENCES user(id),
	PRIMARY KEY (id)
);
